name: Coding standards
on:
  push:
    branches:
      - master

jobs:
  ecs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.0' ]

    name: PHP ${{ matrix.php }} - Coding Standards
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install PHP dependencies
        run: composer install --no-progress

      - name: Check coding standards
        run: vendor/bin/ecs check -c ecs.php
